---
- hosts: all
  become: true
  roles:
    - role: cis_rhel9
      when: ansible_distribution == "Redhat" and ansible_distribution_major_version == "9"
    - role: cis_rhel8
      when: ansible_distribution == "RedHat" and ansible_distribution_major_version == "8"
    - role: qualysguard
    - role: crowdstrike