---
- name: Download {{ ssm_package }}.rpm
  get_url:
    url: "{{ ssm_package_url }}"
    dest: "/{{ ssm_temp_path }}/{{ ssm_package }}.rpm"
    timeout: "{{ ssm_global_downloads_timeout }}"
  tags:
    - download
    - install

- name: Install {{ ssm_package }}.rpm
  dnf:
    name: "/{{ ssm_temp_path }}/{{ ssm_package }}.rpm"
    disable_gpg_check: true
    state: present
  when: not ssm_update
  tags:
    - install

- name: Install/Update {{ ssm_package }}.rpm
  dnf:
    name: "/{{ ssm_temp_path }}/{{ ssm_package }}.rpm"
    disable_gpg_check: true
    state: latest
  when: ssm_update
  tags:
    - install
