---
- name: update apt cache
  apt:
    update_cache: true
    cache_valid_time: 86400
  tags:
    - update-cache

- name: Download {{ ssm_package }}.deb
  get_url:
    url: "{{ ssm_package_url }}"
    dest: "/{{ ssm_temp_path }}/{{ ssm_package }}.deb"
    timeout: "{{ ssm_global_downloads_timeout }}"
  tags:
    - download
    - install

- name: Install {{ ssm_package }}.deb
  apt:
    deb: "/{{ ssm_temp_path }}/{{ ssm_package }}.deb"
    state: present
  when: not ssm_update
  tags:
    - install

- name: Install {{ ssm_package }}.deb
  apt:
    deb: "/{{ ssm_temp_path }}/{{ ssm_package }}.deb"
    state: latest
  when: ssm_update
  tags:
    - install
