---
# references
# https://docs.aws.amazon.com/systems-manager/latest/userguide/ssm-agent.html

- name: Get amazon linux version from "uname" command
  shell: >
    awk -v FS="recipe_name=" 'NF>1{print $2}' /etc/image-id | tr -d '"' | awk '{print $1}'
  ignore_errors: true
  register: amazon_linux_recipe_name_result
  when: >
    ansible_os_family == 'RedHat' and
    ansible_distribution == 'Amazon'
  changed_when: false

# Define facts to manage amazon linux version in a easy way
- name: Set fact "amazon_linux_distribution_version" for amazon linux 1
  set_fact:
    amazon_linux_distribution_version: 1
  when: >
    ansible_os_family == 'RedHat' and
    ansible_distribution == 'Amazon' and
    amazon_linux_recipe_name_result.stdout == 'amzn'

- name: Set fact "amazon_linux_distribution_version" for amazon linux 2
  set_fact:
    amazon_linux_distribution_version: 2
  when: >
    ansible_os_family == 'RedHat' and
    ansible_distribution == 'Amazon' and
    amazon_linux_recipe_name_result.stdout == 'amzn2'

# Selective include of vars
- name: Include variables for RedHat
  include_vars: "{{ item }}"
  with_first_found:
    - "redhat.yml"
    - "main.yml"
  when: >
    ansible_os_family == 'RedHat' and
    ansible_distribution == 'RedHat'
    and (
      ansible_distribution_major_version == '8' or
      ansible_distribution_major_version == '7' or
      ansible_distribution_major_version == '6'
    )
  tags:
    - include-redhat-vars

- name: Include variables for CentOS
  include_vars: "{{ item }}"
  with_first_found:
    - "centos.yml"
    - "main.yml"
  when: >
    ansible_os_family == 'RedHat' and
    ansible_distribution == 'CentOS'
    and (
      ansible_distribution_major_version == '8' or
      ansible_distribution_major_version == '7' or
      ansible_distribution_major_version == '6'
    )
  tags:
    - include-centos-vars

- name: include variables for Amazon Linux
  include_vars: "{{ item }}"
  with_first_found:
    - "amazon.yml"
    - "main.yml"
  when: >
    ansible_os_family == 'RedHat' and
    ansible_distribution == 'Amazon'
  tags:
    - include-amazon-vars

- name: Include variables for Debian
  include_vars: "{{ item }}"
  with_first_found:
    - "debian.yml"
    - "main.yml"
  when: >
    ansible_os_family == 'Debian' and
    ansible_distribution == 'Debian'
  tags:
    - include-debian-vars

- name: Include variables for Ubuntu
  include_vars: "{{ item }}"
  with_first_found:
    - "ubuntu.yml"
    - "main.yml"
  when: >
    ansible_os_family == 'Debian' and
    ansible_distribution == 'Ubuntu'
  tags:
    - include-ubuntu-vars

# Installation tasks
- name: Include tasks for installation on RedHat/CentOS
  include_tasks: "install-{{ ansible_os_family|lower }}-{{ ansible_distribution_major_version }}.yml"
  when: >
    ansible_os_family == 'RedHat' and (
      ansible_distribution == 'CentOS' or
      ansible_distribution == 'RedHat'
    )
  tags:
    - include-redhat-tasks

- name: Include tasks for installation on Amazon Linux
  include_tasks: "install-{{ ansible_distribution|lower }}-{{ amazon_linux_distribution_version }}.yml"
  when: >
    ansible_os_family == 'RedHat' and (
      ansible_distribution == 'Amazon'
    )
  tags:
    - include-amazon-tasks

- name: Include tasks for installation on Debian
  include_tasks: "install-{{ ansible_os_family|lower }}.yml"
  when: >
    ansible_os_family == 'Debian' and (
      ansible_distribution == 'Debian'
    )
  tags:
    - include-debian-tasks

- name: Include tasks for installation on Ubuntu
  include_tasks: "install-{{ ansible_distribution|lower }}.yml"
  when: >
    ansible_os_family == 'Debian' and (
      ansible_distribution == 'Ubuntu'
    )
  tags:
    - include-ubuntu-tasks

# Configure tasks
- name: Include tasks for configure {{ ssm_package }} on RedHat/CentOS
  include_tasks: "configure-{{ ansible_os_family|lower }}-{{ ansible_distribution_major_version }}.yml"
  when: >
    ansible_os_family == 'RedHat' and (
      ansible_distribution == 'CentOS' or
      ansible_distribution == 'RedHat'
    )
  tags:
    - include-configure-redhat

- name: Include tasks for configure {{ ssm_package }} on Amazon Linux
  include_tasks: "configure-{{ ansible_distribution|lower }}-{{ amazon_linux_distribution_version }}.yml"
  when: >
    ansible_os_family == 'RedHat' and (
      ansible_distribution == 'Amazon'
    )
  tags:
    - include-configure-amazon

- name: Include tasks for configure {{ ssm_package }} on Debian
  include_tasks: "configure-{{ ansible_distribution|lower }}.yml"
  when: >
    ansible_os_family == 'Debian' and
    ansible_distribution == 'Debian'
  tags:
    - include-configure-debian

- name: Include tasks for configure {{ ssm_package }} on Ubuntu
  include_tasks: "configure-{{ ansible_distribution|lower }}.yml"
  when: >
    ansible_os_family == 'Debian' and
    ansible_distribution == 'Ubuntu'
  tags:
    - include-configure-ubuntu
